# Generated by Django 2.1.1 on 2018-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181016_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
