# Generated by Django 2.1.1 on 2018-11-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20181101_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacaogerada',
            name='id',
        ),
        migrations.AlterField(
            model_name='adapters',
            name='ativo',
            field=models.IntegerField(choices=[(1, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='recomendacaogerada',
            name='rid',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
