# Generated by Django 2.1.1 on 2018-11-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20181101_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacaoacessada',
            name='id',
        ),
        migrations.AddField(
            model_name='recomendacaoacessada',
            name='idRows',
            field=models.CharField(default='0', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='recomendacaogerada',
            name='idRows',
            field=models.CharField(default='0', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recomendacaoacessada',
            name='idClick',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='webapp.Post'),
        ),
        migrations.AlterField(
            model_name='recomendacaoacessada',
            name='rid',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='webapp.Adapters'),
        ),
        migrations.AlterField(
            model_name='recomendacaogerada',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Adapters'),
        ),
    ]
