# Generated by Django 2.1.1 on 2018-11-08 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20181108_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendacaogerada',
            old_name='idRows',
            new_name='idFileira',
        ),
        migrations.AddField(
            model_name='recomendacaogerada',
            name='idClick',
            field=models.ForeignKey(default=0, max_length=250, on_delete=django.db.models.deletion.CASCADE, to='webapp.Post'),
        ),
        migrations.AlterField(
            model_name='recomendacaoacessada',
            name='idClick',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='webapp.Post'),
        ),
    ]
