# Generated by Django 2.1.7 on 2019-03-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_auto_20190308_1701'),
        ('webapp', '0039_auto_20190306_1342'),
    ]

    operations = [
    ]
