# Generated by Django 2.1.7 on 2019-04-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_auto_20190317_1533'),
        ('webapp', '0040_merge_20190312_1600'),
    ]

    operations = [
    ]
